name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - uses: mise-action/mise-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: mise run install-dev

      - name: Run tests
        run: mise run test

      - name: Run linter
        run: mise run lint

  deploy:
    needs: test
    runs-on: ubuntu-24.04-arm
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6

      - uses: mise-action/mise-action@v3
        with:
          version: latest

      - name: Build
        run: mise run build

      - name: Deploy
        run: |
          sam deploy \
            --region eu-west-2 \
            --stack-name wednesdaybot \
            --parameter-overrides "MastodonAccessToken=${{ secrets.MASTODON_ACCESS_TOKEN }}" \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
